### ISSUE TITLE
Reliance on files in the gitignore file

### ISSUE THREAD

**Issue by c-voulgaris** [byu-transpolab/alameda_destinationchoice#4]
I can't knit a couple of sections that rely on files that are included in the GitIgnore files. Any chance you could edit the method and application sections so they don't use those files (perhaps by creating files that only include the summarized data and referring to those in the Rmd files instead of the files that are listed in GitIgnore?)?

**Comment by c-voulgaris** [comment]
The latest commit doesn't totally fix this - you still need to remove line park_flows.rds from the GitIgnore file and make sure that file is in the repo.

**Comment by c-voulgaris** [comment]
Same with logitdata.rds - you need to remove lines 17 and 18 from the GitIgnore file.

**Comment by gregmacfarlane** [comment]
I don't think this is relevant anymore
